### ISSUE TITLE
a few mistakes with app

### ISSUE THREAD

**Issue by hcgiub001** [pc035860/YCS-cont#7]
1/ the likes on your app is 1 more than what YouTube says

2/If a comment has more than 1k likes, it doesn't show as any likes

3/If I search for multiple words, it comes out empty. I also tried with "" , but nothing comes up

**Comment by hcgiub001** [comment]
you can search for phrases using "extended search" though it doesn't highlight the phrase

**Comment by hcgiub001** [comment]
> I've encountered the same issue. Is it because YT represents comments with thousands of likes as "k" (e.g. 1100 likes = 1.1k, 25000 = 25k, etc.)?

yeah that's what I thought, when it see's a k , the app doesn't show the likes.

**Comment by hcgiub001** [comment]
thank you
issue 1 and 2 is great.
regarding issue 3
using this video as example
https://www.youtube.com/watch?v=Nl_eJ-zdLrA

and search for "kind of clever"

produces the right comment, but as you can see It's also trying to highlight words beginning with "of" and "cle"
It picked up "circlejerk" for cle.

I would love if it could highlight only the term  "kind of clever" and nothing else. otherwise extension is great thanks

**Comment by pc035860** [comment]
> I would love if it could highlight only the term "kind of clever" and nothing else. otherwise extension is great thanks

About the search and filter buttons, I anticipated a lot of behavior inconsistency. However, they are quite obvious if you inspect the code directly. This leads me to believe they were intentionally designed this way. I think only the original author can answer this question...

Regardless, I'll try to adjust the search results in a more reasonable way. Thanks for your example.

**Comment by hcgiub001** [comment]
If you go to https://github.com/sonigy/YCS/issues/56#issuecomment-2143792541
 and at the bottom it says

"This form of advanced searching allows you to fine-tune results.

White space acts as an AND operator, while a single pipe (|) character acts as an OR operator. To escape white space, use double quote ex. ="scheme language" for exact match."

Maybe this is the reason why he kept the search this way?
I'll leave it up to you to see what you want to do with it. :)

**Comment by hcgiub001** [comment]
is extended search working like original author listed on his github? looks like a cool advance search.
right now I can't understand the difference.

also here https://www.youtube.com/watch?v=vukiveN_Ag8
if you search "ram"
 
it brings up words like "parameters" "frame"
so I tried extended search
typed 
=ram
for exact search, empty
then I tried 
^ram
(prefix-exact-match)
and nothing. seems the original author wanted more control over search but it's not working even for basic search

**Comment by pc035860** [comment]
> is extended search working like original author listed on his github? looks like a cool advance search. right now I can't understand the difference.

I haven't made any changes to the extended search functionality, so it should operate as it did before.

The confusion may arise from the term "item" in the description. Here, "item" refers to the entire text chunk rather than a single word. Therefore, you should consider the whole comment as an item.

<img src="https://github.com/pc035860/YCS-cont/assets/811518/22fd0799-3626-49b5-90e1-7c4ed68b544b" width="400" />


So, in the case of the transcript in your example video above, the correct way to search for the word `ram` is to use `" ram "` or `'" ram "` (to avoid matching fuzzy results).

<img src="https://github.com/pc035860/YCS-cont/assets/811518/03e58bc0-4d00-4b6c-9498-d317b8cab8a2" width="400" />


Text searching in the extension is conducted via [Fuse.js](https://www.fusejs.io/examples.html#extended-search) with the options below (useExtendedSearch is set to true when extended search is enabled):

```js
{
  "isCaseSensitive": false,
  "findAllMatches": false,
  "includeMatches": false,
  "includeScore": true,
  "ignoreLocation": true,
  "useExtendedSearch": false,
  "minMatchCharLength": 1,
  "shouldSort": true,
  "threshold": 0.15,
  "distance": 100000
}
```

**Comment by hcgiub001** [comment]
thanks it's much better.
